"""
=============================================================================
DLM model verification — 5 diagnostic levels
=============================================================================

Ozone version, ported from DLM/dlmpython_ch4/verif_modele.py with the
fixes introduced during the critical review of the CH4 methodology:

Level 1: Innovation v(t) diagnostics
-> The filter residuals must be Gaussian white noise.
-> SEASONAL heteroscedasticity test (Levene by calendar month, not a
  simple chronological first-half/second-half variance ratio); Ljung-Box
  reduced to 2 lags (1, 12) with Bonferroni correction instead of 4
  uncorrected tests (otherwise P(reject wrongly >=1 time) ~18% even
  under white noise).

Level 2: MCMC convergence
-> Audit with 4 independent chains, dispersed starting points: a proper
  R-hat (rank-normalized split-Rhat, Vehtari et al. 2021) and ESS via
  Geyer's (1992) initial positive sequence, instead of a single chain
  with a crude AR(1) approximation that can detect neither a hidden
  mode nor poor autocorrelation decay.

Level 3: Synthetic-data test
-> y(t) is generated by direct simulation of the full state-space model
  (G, F, Q) with KNOWN parameters, the pipeline is run, and we check
  that the injected values are recovered.

Level 4: Leave-one-year-out (cross-validation)
-> One year of data is removed, predicted with the model (forward
  filter, no information leakage from the future), and compared to the
  true value.

Level 5: DLM vs MLR comparison
-> DIC (Spiegelhalter et al. 2002), not the naive AIC with k=hyperparameters
  alone, which undercounts the effective degrees of freedom of a model
  with a smoothed stochastic trend. R^2 is kept for information only
  (the DLM structurally nests the MLR, so R^2_DLM >= R^2_MLR is nearly
  guaranteed by construction and proves nothing). The MLR's AIC includes
  the full Gaussian constant (n*(1+ln 2pi)) to stay on the same scale as
  the Kalman filter's likelihood -- omitting it would systematically
  bias the comparison in favor of the MLR.
=============================================================================
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from matplotlib.ticker import AutoMinorLocator
from scipy import stats
from scipy.stats import normaltest, shapiro, kstest
from pathlib import Path
import warnings
warnings.filterwarnings("ignore")

import sys, io
sys.path.insert(0, ".")
from step1_ssm_matrices import make_G, make_F, make_Q, make_R, N_STATE, RHO, AR_IDX, FREQS
from step2_kalman_filter import kalman_filter
from step3_rts_smoother import kalman_smoother
from step4_simulation_smoother import simulation_smoother
from step5_mcmc import make_prior, run_mcmc, run_mcmc_multichain, _sigmoid

OUTPUT_DIR = Path("outputPlanD")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

# ─── COLORS ─────────────────────────────────────────────────────────────────
C = dict(dark="#161b22", grid="#2a2d3e", text="#e0e0e0",
         red="#ff6b6b", blue="#4fc3f7", green="#66bb6a",
         amber="#ffa726", purp="#ce93d8")


def _setup_dark(fig):
    fig.patch.set_facecolor(C["dark"])
    plt.rcParams.update({"text.color": C["text"], "axes.labelcolor": C["text"],
                          "xtick.color": C["text"], "ytick.color": C["text"],
                          "axes.facecolor": C["dark"], "axes.edgecolor": C["grid"]})


# ═══════════════════════════════════════════════════════════════════════════════
# RIGOROUS MCMC DIAGNOSTICS (rank-normalized split-Rhat + Geyer ESS)
# ═══════════════════════════════════════════════════════════════════════════════

def _rank_normalize(x: np.ndarray) -> np.ndarray:
    """Rank -> normal transform (Vehtari et al. 2021), robust to heavy
    tails -- used for the split-Rhat instead of the raw values."""
    ranks = stats.rankdata(x, method="average")
    n = len(x)
    return stats.norm.ppf((ranks - 3/8) / (n - 1/4 + 1))


def _split_rhat(chains_list: list) -> float:
    """
    Rank-normalized split-Rhat (Vehtari et al. 2021, bulk-only version).
    Each chain is cut into 2 halves, treated as additional independent
    chains: detects both a lack of convergence between chains AND
    non-stationarity within a chain.
    """
    split = []
    for c in chains_list:
        n = len(c)
        h = n // 2
        split.append(c[:h])
        split.append(c[h:2*h])
    n = len(split[0])
    m = len(split)
    pooled = np.concatenate(split)
    z_pooled = _rank_normalize(pooled)
    z_split = [z_pooled[i*n:(i+1)*n] for i in range(m)]
    means = np.array([s.mean() for s in z_split])
    B = n * np.var(means, ddof=1)
    W = np.mean([np.var(s, ddof=1) for s in z_split])
    if W <= 0:
        return np.nan
    var_hat = (n - 1) / n * W + B / n
    return float(np.sqrt(var_hat / W))


def _autocorr_1d(x: np.ndarray, max_lag: int) -> np.ndarray:
    x = x - x.mean()
    n = len(x)
    var = np.dot(x, x) / n
    if var <= 0:
        return np.zeros(max_lag + 1)
    return np.array([np.dot(x[:n-lag], x[lag:]) / n / var
                     for lag in range(max_lag + 1)])


def _geyer_ess(chains_list: list) -> float:
    """
    ESS via Geyer's (1992) initial positive sequence, averaged over
    several chains -- replaces the crude AR(1) approximation.
    """
    n = len(chains_list[0])
    m = len(chains_list)
    max_lag = min(n - 2, 500)
    acfs = np.array([_autocorr_1d(c, max_lag) for c in chains_list])
    acf_mean = acfs.mean(axis=0)

    tau = 1.0
    t = 1
    while t < max_lag - 1:
        pair = acf_mean[t] + acf_mean[t + 1]
        if pair < 0:
            break
        tau += 2 * pair
        t += 2
    tau = max(tau, 1e-6)
    return max((n * m) / tau, 1.0)


# ═══════════════════════════════════════════════════════════════════════════════
# LEVEL 1 — INNOVATION DIAGNOSTICS
# ═══════════════════════════════════════════════════════════════════════════════

def check_innovations(kf_result: dict,
                      dates: pd.DatetimeIndex | None = None,
                      title: str = "Innovation diagnostics") -> dict:
    """
    LEVEL 1: Checks that the innovations v(t) are Gaussian white noise.

    dates : index of the observations, used to group the
        heteroscedasticity test by calendar month (Test 4) rather than
        a simple chronological split into 2 halves, which cannot detect
        seasonal heteroscedasticity (e.g. sonde/FTIR retrieval noise
        stronger in the polar winter).
    """
    v = kf_result["v"]
    S = kf_result["S"]
    mask = ~np.isnan(v) & ~np.isnan(S) & (S > 0)
    if dates is not None:
        dates = dates[mask]
    v = v[mask]
    S = S[mask]
    v_std = v / np.sqrt(S)
    n = len(v)

    print(f"\n{'='*60}")
    print(f" LEVEL 1 — INNOVATION DIAGNOSTICS: {title}")
    print(f"{'='*60}")

    # ── Test 1: zero mean ─────────────────────────────────────────────
    t_stat, p_mean = stats.ttest_1samp(v_std, 0)
    ok_mean = p_mean > 0.05
    print(f"\n Test 1 — Zero mean (t-test):")
    print(f" Mean = {v_std.mean():.4f} (should be ~ 0)")
    print(f" p = {p_mean:.4f} -> {'OK' if ok_mean else 'PROBLEM'}")

    # ── Test 2: normality (Shapiro-Wilk on a subsample) ────────────
    sample = v_std[:min(n, 500)]
    _, p_norm = shapiro(sample)
    ok_norm = p_norm > 0.05
    print(f"\n Test 2 — Normality (Shapiro-Wilk):")
    print(f" p = {p_norm:.4f} -> {'OK' if ok_norm else 'WARNING'}")

    # ── Test 3: autocorrelation (Ljung-Box, lags 1 and 12, Bonferroni) ────
    from statsmodels.stats.diagnostic import acorr_ljungbox
    alpha_corr = 0.05 / 2
    lb = acorr_ljungbox(v_std, lags=[1, 12], return_df=True)
    p_lb = lb["lb_pvalue"].values
    ok_lb = np.all(p_lb > alpha_corr)
    print(f"\n Test 3 — Autocorrelation (Ljung-Box, Bonferroni threshold {alpha_corr:.3f}):")
    for lag, p in zip([1, 12], p_lb):
        flag = "OK" if p > alpha_corr else "AUTOCORRELATION"
        print(f" lag={lag:2d} p={p:.4f} -> {flag}")
    print(f" Conclusion: {'OK' if ok_lb else 'AUTOCORR'}")

    # ── Test 4: SEASONAL heteroscedasticity (Levene, 12 months) ─────────
    if dates is not None:
        months = dates.month.values
        groups = [v_std[months == m] for m in range(1, 13)]
        groups = [g for g in groups if len(g) >= 3]
        if len(groups) >= 2:
            _, p_het = stats.levene(*groups, center="median")
            ok_het = p_het > 0.05
            print(f"\n Test 4 — Seasonal homoscedasticity (Levene, {len(groups)} months):")
            print(f" p = {p_het:.4f} -> {'OK' if ok_het else 'HETEROSCEDASTICITY'}")
        else:
            ok_het, p_het = True, np.nan
            print(f"\n Test 4 — Homoscedasticity: not enough distinct months, skipped")
    else:
        mid = len(v_std) // 2
        var1 = np.var(v_std[:mid])
        var2 = np.var(v_std[mid:])
        ratio = max(var1, var2) / min(var1, var2)
        ok_het = ratio < 2.0
        p_het = np.nan
        print(f"\n Test 4 — Homoscedasticity (fallback, no dates):")
        print(f" 1st/2nd-half ratio = {ratio:.2f} -> {'OK' if ok_het else 'HETEROSCEDASTICITY'}")

    # ── Summary ─────────────────────────────────────────────────────────────
    all_ok = ok_mean and ok_norm and ok_lb and ok_het
    print(f"\n SUMMARY: {'Model well specified' if all_ok else 'Check the model'}")
    if not ok_lb:
        print(" -> Suggestion: increase sigma_trend or add an AR term")
    if not ok_norm:
        print(" -> Suggestion: check for outliers in the data")

    # ── Figure ─────────────────────────────────────────────────────────────
    fig = plt.figure(figsize=(14, 10))
    _setup_dark(fig)
    gs = gridspec.GridSpec(2, 2, figure=fig, hspace=0.4, wspace=0.35)
    t_idx = np.arange(n)

    ax1 = fig.add_subplot(gs[0, :])
    ax1.plot(t_idx, v_std, lw=0.8, color=C["blue"], alpha=0.7)
    ax1.axhline(0, color="#888", lw=0.8)
    ax1.axhline(2, color=C["amber"], lw=0.8, ls="--", alpha=0.6)
    ax1.axhline(-2, color=C["amber"], lw=0.8, ls="--", alpha=0.6,
                label="+/-2 sigma (95% expected)")
    pct_out = 100 * np.mean(np.abs(v_std) > 2)
    ax1.set_title(
        f"Standardized innovations v(t)/sqrt(S(t)) — {pct_out:.1f}% > 2 sigma "
        f"(expected 5%)",
        fontsize=11, color=C["text"])
    ax1.set_ylabel("v/sqrt(S)", fontsize=10)
    ax1.legend(fontsize=8.5, framealpha=0.3)
    ax1.grid(color=C["grid"], lw=0.6)

    ax2 = fig.add_subplot(gs[1, 0])
    x_ref = np.linspace(-4, 4, 200)
    ax2.hist(v_std, bins=30, density=True, color=C["blue"], alpha=0.6,
             label="Observed innovations")
    ax2.plot(x_ref, stats.norm.pdf(x_ref), color=C["red"], lw=2,
             label="Theoretical N(0,1)")
    ax2.set_title(f"Distribution (Shapiro p={p_norm:.3f})",
                  fontsize=10, color=C["text"])
    ax2.legend(fontsize=8.5, framealpha=0.3)
    ax2.grid(color=C["grid"], lw=0.6)

    ax3 = fig.add_subplot(gs[1, 1])
    stats.probplot(v_std, dist="norm", plot=ax3)
    ax3.get_lines()[0].set(color=C["blue"], alpha=0.6, markersize=3)
    ax3.get_lines()[1].set(color=C["red"], lw=2)
    ax3.set_title("Q-Q plot (should be a straight line)", fontsize=10,
                  color=C["text"])
    ax3.grid(color=C["grid"], lw=0.6)

    plt.savefig(OUTPUT_DIR / "verif1_innovations.png",
                dpi=150, bbox_inches="tight", facecolor=fig.get_facecolor())
    plt.close()
    print(f"\n -> Figure: {OUTPUT_DIR}/verif1_innovations.png")

    return {"ok": all_ok, "p_mean": p_mean, "p_norm": p_norm,
            "p_lb": p_lb, "p_het": p_het}


# ═══════════════════════════════════════════════════════════════════════════════
# LEVEL 2 — MCMC CONVERGENCE (multi-chain audit)
# ═══════════════════════════════════════════════════════════════════════════════

def check_mcmc_convergence(
    y: np.ndarray,
    prior: dict | None = None,
    n_chains: int = 4,
    n_iter: int = 3000,
    n_burnin: int = 1000,
    proxies: np.ndarray | None = None,
    beta: np.ndarray | None = None,
) -> dict:
    """
    LEVEL 2: Convergence audit using 4 independent MCMC chains with
    dispersed starting points. Rhat (rank-normalized split-Rhat) + Geyer
    ESS, instead of a single chain with an AR(1) approximation.
    """
    if prior is None:
        prior = make_prior(y)

    print(f"\n{'='*60}")
    print(f" LEVEL 2 — MCMC CONVERGENCE ({n_chains} chains, audit)")
    print(f"{'='*60}")

    mc = run_mcmc_multichain(y, prior, n_chains=n_chains, n_iter=n_iter,
                             n_burnin=n_burnin, proxies=proxies, beta=beta)
    chains_list = mc["chains_list"]
    d = chains_list[0].shape[1]
    all_names = ["log sigma_trend", "log sigma_seas", "log sigma_obs", "log sigma_ar", "logit rho"]
    names = all_names[:d]
    n = chains_list[0].shape[0]

    print(f" {n_chains} chains x {n} post-burn-in samples")
    print(f" Mean acceptance rate: {mc['accept_rate']:.1%} "
          f"({'OK' if 0.10 < mc['accept_rate'] < 0.50 else 'WARNING'})")

    fig, axes = plt.subplots(d, 3, figsize=(14, 3.3 * d), squeeze=False)
    fig.suptitle(f"MCMC diagnostics ({n_chains} chains)", fontsize=13)
    _setup_dark(fig)

    rhat_list, ess_list = [], []
    chain_colors = [C["blue"], C["red"], C["green"], C["amber"], C["purp"]]
    for i, name in enumerate(names):
        per_chain = [chains_list[c][:, i] for c in range(n_chains)]
        pooled = np.concatenate(per_chain)
        param_pooled = _sigmoid(pooled) if name == "logit rho" else np.exp(pooled)

        ax = axes[i, 0]
        for c in range(n_chains):
            ax.plot(per_chain[c], lw=0.5,
                    color=chain_colors[c % len(chain_colors)], alpha=0.7)
        ax.set_title(f"Trace ({n_chains} chains) — {name}", fontsize=9, color=C["text"])
        ax.set_xlabel("Iteration", fontsize=8)
        ax.grid(color=C["grid"], lw=0.4)

        ax = axes[i, 1]
        max_lag = min(100, n // 4)
        acf_mean = _autocorr_1d(per_chain[0], max_lag)
        lags = np.arange(0, max_lag + 1)
        ax.bar(lags, acf_mean, color=C["blue"], alpha=0.6, width=0.8)
        ax.axhline(1.96/np.sqrt(n), color=C["amber"], ls="--", lw=1)
        ax.axhline(-1.96/np.sqrt(n), color=C["amber"], ls="--", lw=1)
        ax.set_title(f"Autocorrelation — {name}", fontsize=9, color=C["text"])
        ax.set_xlabel("Lag", fontsize=8)
        ax.grid(color=C["grid"], lw=0.4)

        ax = axes[i, 2]
        ax.hist(param_pooled, bins=40, density=True, color=C["green"], alpha=0.6)
        med = np.median(param_pooled)
        lo, hi = np.percentile(param_pooled, [2.5, 97.5])
        ax.axvline(med, color=C["red"], lw=1.5, label=f"Median={med:.5f}")
        ax.axvspan(lo, hi, alpha=0.15, color=C["red"],
                   label=f"CI95=[{lo:.5f},{hi:.5f}]")
        ax.set_title(f"Posterior — {name}", fontsize=9, color=C["text"])
        ax.legend(fontsize=7, framealpha=0.3)
        ax.grid(color=C["grid"], lw=0.4)

        rhat = _split_rhat(per_chain)
        ess = _geyer_ess(per_chain)
        rhat_list.append(rhat)
        ess_list.append(ess)
        ok_rhat = rhat < 1.01
        ok_ess = ess > 400
        print(f"\n {name}:")
        print(f" Median = {med:.6f} CI95=[{lo:.6f}, {hi:.6f}]")
        print(f" Rhat = {rhat:.4f} -> {'OK' if ok_rhat else 'NOT CONVERGED (Rhat > 1.01)'}")
        print(f" ESS (Geyer) = {ess:.0f} -> {'OK' if ok_ess else 'ESS too low'}")

    plt.tight_layout()
    plt.savefig(OUTPUT_DIR / "verif2_mcmc.png",
                dpi=150, bbox_inches="tight", facecolor=fig.get_facecolor())
    plt.close()
    print(f"\n -> Figure: {OUTPUT_DIR}/verif2_mcmc.png")

    all_ok = all(r < 1.01 for r in rhat_list) and all(e > 400 for e in ess_list)
    print(f"\n LEVEL 2 SUMMARY: {'Multi-chain convergence confirmed' if all_ok else 'Convergence doubtful'}")

    return {"rhat": rhat_list, "ess": ess_list, "ok": all_ok, "names": names}


# ═══════════════════════════════════════════════════════════════════════════════
# LEVEL 3 — SYNTHETIC-DATA TEST (the most fundamental)
# ═══════════════════════════════════════════════════════════════════════════════

def test_synthetic_recovery(
    n: int = 450,
    true_sigma_trend: float = 0.0003,
    true_sigma_seas: float = 0.008,
    true_sigma_obs: float = 0.04,
    true_sigma_ar: float = 0.0,
    true_rho: float = RHO,
    true_trend_dec: float = 1.5,   # %/dec
    n_mcmc: int = 3000,
    seed: int = 42,
) -> dict:
    """
    LEVEL 3: Recovery test on synthetic data (5 parameters, including the
    AR(1) state). Generated by direct simulation of the state-space model
    (G, F, Q): guarantees that the synthetic data are exactly consistent
    with the model fitted by MCMC.
    """
    np.random.seed(seed)
    print(f"\n{'='*60}")
    print(f" LEVEL 3 — SYNTHETIC-DATA TEST")
    print(f"{'='*60}")
    print(f"\n Injected parameters:")
    print(f" sigma_trend = {true_sigma_trend:.5f}")
    print(f" sigma_seas = {true_sigma_seas:.4f}")
    print(f" sigma_obs = {true_sigma_obs:.4f}")
    print(f" sigma_ar = {true_sigma_ar:.5f}")
    print(f" rho = {true_rho:.4f}")
    print(f" trend = {true_trend_dec:+.2f} %/dec")

    t_mo = np.arange(n, dtype=float)

    G = make_G(true_rho)
    F = make_F()[0]
    Q = make_Q(true_sigma_trend, true_sigma_seas, true_sigma_ar)

    x = np.zeros(N_STATE)
    x[1] = true_trend_dec / 100 / 120
    for k in range(len(FREQS)):
        x[2 + 2*k] = 0.12 if k == 0 else 0.04

    states = np.zeros((n, N_STATE))
    for i in range(n):
        if i > 0:
            w = np.random.multivariate_normal(np.zeros(N_STATE), Q)
            x = G @ x + w
        states[i] = x

    harm_idx = [2 + 2*k for k in range(len(FREQS))]
    true_signal = states[:, 0] + states[:, harm_idx].sum(axis=1)

    # Trend REALIZED by the simulated random walk, distinct from the
    # INITIAL slope injected (true_trend_dec): over a window of n
    # months, even a modest sigma_trend accumulates a drift with std
    # sigma_trend*sqrt(n)*12000 (%/dec) that can far exceed the initial
    # slope -- comparing the MCMC estimate to the initial slope rather
    # than to the actually realized mean trend would produce a false
    # failure (the random walk, not the pipeline, would have "drifted").
    t_true = np.arange(n, dtype=float)
    A_true = np.column_stack([np.ones(n), t_true])
    c_true, *_ = np.linalg.lstsq(A_true, states[:, 0], rcond=None)
    true_trend_realized = c_true[1] * 120 * 100

    obs_noise = np.random.normal(0, true_sigma_obs, n)
    y = states @ F + obs_noise

    missing = np.random.choice(n, size=int(0.05*n), replace=False)
    y[missing] = np.nan

    print(f"\n Series generated: {n} months, {len(missing)} NaN "
          f"({len(missing)/n:.0%})")

    kf_true = kalman_filter(y, true_sigma_obs, true_sigma_trend,
                            true_sigma_seas, true_sigma_ar, rho=true_rho)
    ks_true = kalman_smoother(kf_true, rho=true_rho)

    prior = make_prior(y)
    mcmc_r = run_mcmc(y, prior, n_iter=n_mcmc, n_burnin=1000,
                      verbose=False)

    print(f"\n MCMC results:")
    all_inside = True
    for name, true_val, samp in [
        ("sigma_trend", true_sigma_trend, mcmc_r["sigma_trend"]),
        ("sigma_seas", true_sigma_seas, mcmc_r["sigma_seas"]),
        ("sigma_obs", true_sigma_obs, mcmc_r["sigma_obs"]),
        ("sigma_ar", true_sigma_ar, mcmc_r["sigma_ar"]),
        ("rho", true_rho, mcmc_r["rho"]),
    ]:
        lo, hi = np.percentile(samp, [2.5, 97.5])
        inside = lo <= true_val <= hi
        if not inside:
            all_inside = False
        print(f" {name:<12} : true={true_val:.5f} "
              f"CI95=[{lo:.5f},{hi:.5f}] "
              f"{'INSIDE CI' if inside else 'OUTSIDE CI'}")

    sigma_t = np.median(mcmc_r["sigma_trend"])
    sigma_s = np.median(mcmc_r["sigma_seas"])
    sigma_o = np.median(mcmc_r["sigma_obs"])
    sigma_a = np.median(mcmc_r["sigma_ar"])
    rho_est = np.median(mcmc_r["rho"])
    kf_est = kalman_filter(y, sigma_o, sigma_t, sigma_s, sigma_a, rho=rho_est)
    ks_est = kalman_smoother(kf_est, rho=rho_est)
    sim_est = simulation_smoother(ks_est, n_samples=200)

    t_arr = np.arange(n, dtype=float)
    trends = []
    for k in range(sim_est["level_samp"].shape[0]):
        mu = sim_est["level_samp"][k]
        valid = ~np.isnan(mu)
        if valid.sum() > 10:
            A = np.column_stack([np.ones(valid.sum()), t_arr[valid]])
            c, *_ = np.linalg.lstsq(A, mu[valid], rcond=None)
            trends.append(c[1]*120*100)
    trends = np.array(trends)
    trend_est = np.median(trends)
    lo_t, hi_t = np.percentile(trends, [2.5, 97.5])
    inside_t = lo_t <= true_trend_realized <= hi_t

    print(f"\n trend: injected (initial slope)={true_trend_dec:+.2f} %/dec "
          f"realized (random walk)={true_trend_realized:+.2f} %/dec")
    print(f" trend: true={true_trend_realized:+.2f} %/dec "
          f"estimated={trend_est:+.2f} "
          f"CI95=[{lo_t:+.2f},{hi_t:+.2f}] "
          f"{'INSIDE CI' if inside_t else 'OUTSIDE CI'}")

    print(f"\n SUMMARY: "
          f"{'Pipeline correct' if all_inside and inside_t else 'Problem detected'}")

    fig, axes = plt.subplots(2, 1, figsize=(14, 9), sharex=True)
    _setup_dark(fig)
    fig.suptitle("Level 3 — Recovery on synthetic data",
                 fontsize=12, color=C["text"])

    ax1 = axes[0]
    t_valid = np.where(~np.isnan(y))[0]
    ax1.plot(t_valid, y[t_valid], "o", ms=2.5, alpha=0.35, color=C["blue"],
             label="Synthetic y")
    ax1.plot(t_mo, true_signal, lw=1.5, color=C["amber"],
             alpha=0.7, label="True signal (trend + season)")
    ax1.plot(t_mo, ks_est["level"] + ks_est["x_smooth"][:, 2],
             lw=2, color=C["red"], label="Estimated DLM")
    ax1.set_ylabel("Signal", fontsize=10)
    ax1.legend(fontsize=8.5, framealpha=0.3)
    ax1.grid(color=C["grid"], lw=0.6)

    ax2 = axes[1]
    ax2.plot(t_mo, ks_true["slope_dec"], lw=1.5, color=C["amber"],
             label="True slope (known sigma_trend)")
    ax2.plot(t_mo, ks_est["slope_dec"], lw=2, color=C["green"],
             label="Estimated slope (MCMC)")
    ax2.fill_between(t_mo, ks_est["ic_lower"], ks_est["ic_upper"],
                     alpha=0.2, color=C["green"])
    ax2.axhline(true_trend_realized, color=C["red"], ls="--", lw=1,
                label=f"Realized trend = {true_trend_realized:+.1f} %/dec")
    ax2.set_ylabel("nu(t) [%/dec]", fontsize=10)
    ax2.legend(fontsize=8.5, framealpha=0.3)
    ax2.grid(color=C["grid"], lw=0.6)

    plt.savefig(OUTPUT_DIR / "verif3_synthetique.png",
                dpi=150, bbox_inches="tight", facecolor=fig.get_facecolor())
    plt.close()
    print(f"\n -> Figure: {OUTPUT_DIR}/verif3_synthetique.png")

    return {"inside_params": all_inside, "inside_trend": inside_t,
            "trend_est": trend_est, "trend_true": true_trend_realized,
            "trend_injected": true_trend_dec, "mcmc": mcmc_r}


# ═══════════════════════════════════════════════════════════════════════════════
# LEVEL 4 — LEAVE-ONE-YEAR-OUT
# ═══════════════════════════════════════════════════════════════════════════════

def leave_one_year_out(
    y: np.ndarray,
    sigma_trend: float,
    sigma_seas: float,
    sigma_obs: float,
    dates: pd.DatetimeIndex = None,
    n_years_test: int = 5,
    sigma_ar: float = 0.0,
    rho: float = RHO,
) -> dict:
    """
    LEVEL 4: Leave-one-year-out cross-validation.
    """
    n = len(y)
    years = dates.year.unique()
    step = max(1, len(years) // (n_years_test + 1))
    test_years = sorted(years[step::step][:n_years_test])

    print(f"\n{'='*60}")
    print(f" LEVEL 4 — LEAVE-ONE-YEAR-OUT ({n_years_test} years)")
    print(f"{'='*60}")
    print(f" Test years: {list(test_years)}")

    results = []
    all_coverage = []

    for yr in test_years:
        y_masked = y.copy()
        mask_idx = np.where(dates.year == yr)[0]
        y_true = y[mask_idx].copy()
        y_masked[mask_idx] = np.nan

        kf_masked = kalman_filter(y_masked, sigma_obs, sigma_trend,
                                  sigma_seas, sigma_ar, rho=rho)

        F = make_F()
        preds = []
        for i in mask_idx:
            pred_mean = (F @ kf_masked["x_pred"][i])[0]
            pred_var = (F @ kf_masked["P_pred"][i] @ F.T)[0, 0] + sigma_obs**2
            preds.append({"mean": pred_mean, "std": np.sqrt(pred_var)})

        coverage = []
        for j, (i, p) in enumerate(zip(mask_idx, preds)):
            if not np.isnan(y_true[j]):
                in_ic = abs(y_true[j] - p["mean"]) < 1.96 * p["std"]
                coverage.append(in_ic)

        rate = np.mean(coverage) if coverage else np.nan
        all_coverage.extend(coverage)
        rmse = np.sqrt(np.nanmean(
            (y_true - np.array([p["mean"] for p in preds]))**2))
        results.append({"year": yr, "coverage": rate, "rmse": rmse})
        print(f" {yr} : CI95 coverage = {rate:.0%} "
              f"RMSE = {rmse:.4f} "
              f"({'OK' if rate >= 0.80 else 'WARNING'})")

    total_coverage = np.mean(all_coverage)
    print(f"\n Overall coverage: {total_coverage:.1%} "
          f"(expected ~ 95% — "
          f"{'OK' if 0.80 <= total_coverage <= 1.0 else 'WARNING'})")

    return {"results": results, "total_coverage": total_coverage}


# ═══════════════════════════════════════════════════════════════════════════════
# LEVEL 5 — DLM vs MLR COMPARISON
# ═══════════════════════════════════════════════════════════════════════════════

def compare_dlm_mlr(
    y: np.ndarray,
    sigma_trend: float,
    sigma_seas: float,
    sigma_obs: float,
    sigma_ar: float = 0.0,
    proxies: np.ndarray | None = None,
    beta: np.ndarray | None = None,
    rho: float = RHO,
    mcmc_result: dict | None = None,
) -> dict:
    """
    LEVEL 5: Compares the DLM with a simple linear MLR.

    DIC (lower = better) if mcmc_result is provided, otherwise naive AIC.
    R^2 -- INFORMATIVE ONLY, not a decision criterion.
    """
    n = len(y)
    print(f"\n{'='*60}")
    print(f" LEVEL 5 — DLM vs MLR COMPARISON")
    print(f"{'='*60}")

    valid = ~np.isnan(y)
    y_v = y[valid]
    t_v = np.arange(n)[valid].astype(float)

    omega1, omega2 = 2*np.pi/12, 2*np.pi/6
    X_mlr = [np.ones(valid.sum()), t_v,
             np.cos(omega1*t_v), np.sin(omega1*t_v),
             np.cos(omega2*t_v), np.sin(omega2*t_v)]
    if proxies is not None and beta is not None:
        for p in range(proxies.shape[1]):
            X_mlr.append(proxies[valid, p])
    A_mlr = np.column_stack(X_mlr)
    coef_mlr, *_ = np.linalg.lstsq(A_mlr, y_v, rcond=None)
    y_hat_mlr = A_mlr @ coef_mlr
    resid_mlr = y_v - y_hat_mlr
    ss_res_mlr = np.sum(resid_mlr**2)
    ss_tot = np.sum((y_v - y_v.mean())**2)
    r2_mlr = 1 - ss_res_mlr / ss_tot
    k_mlr = A_mlr.shape[1]
    n_v = valid.sum()
    # Full AIC (Gaussian constant included) -- comparable to the Kalman
    # filter's likelihood, which includes it explicitly.
    aic_mlr = n_v * np.log(ss_res_mlr/n_v) + n_v * (1 + np.log(2*np.pi)) + 2*k_mlr
    trend_mlr_dec = coef_mlr[1] * 120 * 100

    kf_dlm = kalman_filter(y, sigma_obs, sigma_trend, sigma_seas,
                           sigma_ar, proxies, beta, rho=rho)
    ks_dlm = kalman_smoother(kf_dlm, rho=rho)

    obs_idx = np.nonzero(make_F()[0])[0]
    y_hat_dlm = sum(ks_dlm["x_smooth"][:, idx][valid]
                    for idx in obs_idx)
    if proxies is not None and beta is not None:
        y_hat_dlm += proxies[valid] @ beta
    resid_dlm = y_v - y_hat_dlm
    ss_res_dlm = np.sum(resid_dlm**2)
    r2_dlm = 1 - ss_res_dlm / ss_tot

    k_dlm_naive = 5
    aic_dlm_naive = -2 * kf_dlm["loglik"] + 2 * k_dlm_naive

    dic_dlm = None
    p_d = None
    if mcmc_result is not None:
        chains = mcmc_result["chains"]
        n_draws = len(chains)
        thin = max(1, n_draws // 500)
        idx = np.arange(0, n_draws, thin)
        st_i = np.exp(chains[idx, 0])
        ss_i = np.exp(chains[idx, 1])
        so_i = np.exp(chains[idx, 2])
        sa_i = np.exp(chains[idx, 3])
        rh_i = _sigmoid(chains[idx, 4])
        logliks = np.array([
            kalman_filter(y, so_i[j], st_i[j], ss_i[j], sa_i[j], proxies, beta,
                         rho=rh_i[j])["loglik"]
            for j in range(len(idx))
        ])
        D_bar = -2 * np.mean(logliks)

        theta_bar_t = chains.mean(axis=0)
        ll_bar = kalman_filter(
            y, np.exp(theta_bar_t[2]), np.exp(theta_bar_t[0]),
            np.exp(theta_bar_t[1]), np.exp(theta_bar_t[3]), proxies, beta,
            rho=_sigmoid(theta_bar_t[4]))["loglik"]
        D_theta_bar = -2 * ll_bar
        p_d = D_bar - D_theta_bar
        dic_dlm = D_bar + p_d
        if p_d < 0:
            print(f"\n (p_D={p_d:.2f} < 0: a known DIC pathology when the "
                  f"posterior is very tight -- not an error in itself, "
                  f"but indicates high sensitivity to the chosen "
                  f"theta_bar point; interpret with caution)")

    print(f"\n {'Metric':<24} {'MLR':>10} {'DLM':>10}")
    print(f" {'-'*46}")
    print(f" {'Naive AIC (k=5)':<24} {'—':>10} {aic_dlm_naive:>10.1f}")
    if dic_dlm is not None:
        print(f" {'DIC (p_D={:.1f})'.format(p_d):<24} {aic_mlr:>10.1f} {dic_dlm:>10.1f} "
              f"{'  DLM better' if dic_dlm < aic_mlr else '  MLR better'}")
    else:
        print(f" {'AIC':<24} {aic_mlr:>10.1f} {aic_dlm_naive:>10.1f} "
              f"{'  DLM better' if aic_dlm_naive < aic_mlr else '  MLR better'}")
    print(f" {'R2 (informative only)':<24} {r2_mlr:>10.4f} {r2_dlm:>10.4f}")
    print(f" {'Trend %/dec':<24} {trend_mlr_dec:>+10.2f} {'(variable)':>10}")

    aic_dlm = dic_dlm if dic_dlm is not None else aic_dlm_naive
    delta_aic = aic_mlr - aic_dlm
    crit_name = "Delta DIC" if dic_dlm is not None else "Delta AIC (naive)"
    if delta_aic > 10:
        print(f"\n {crit_name} = {delta_aic:.1f}: DLM clearly better -> non-linear trend")
    elif delta_aic > 2:
        print(f"\n {crit_name} = {delta_aic:.1f}: DLM slightly better")
    elif delta_aic > -2:
        print(f"\n {crit_name} = {delta_aic:.1f}: DLM and MLR equivalent -> near-linear trend")
    elif delta_aic > -10:
        print(f"\n {crit_name} = {delta_aic:.1f}: MLR slightly better")
    else:
        print(f"\n {crit_name} = {delta_aic:.1f}: MLR clearly better -> the DLM brings "
              f"no net gain once the effective degrees of freedom are counted")

    fig, axes = plt.subplots(1, 2, figsize=(13, 5))
    _setup_dark(fig)
    fig.suptitle("Level 5 — DLM vs MLR", fontsize=12, color=C["text"])

    axes[0].plot(np.arange(valid.sum()), resid_mlr,
                 lw=0.7, color=C["amber"], alpha=0.7, label="MLR residuals")
    axes[0].plot(np.arange(valid.sum()), resid_dlm,
                 lw=0.7, color=C["green"], alpha=0.7, label="DLM residuals")
    axes[0].axhline(0, color="#888", lw=0.8)
    axes[0].set_title(
        f"Residuals | MLR AIC={aic_mlr:.0f} DLM AIC/DIC={aic_dlm:.0f}",
        fontsize=10, color=C["text"])
    axes[0].legend(fontsize=8.5, framealpha=0.3)
    axes[0].grid(color=C["grid"], lw=0.6)

    axes[1].bar(["MLR", "DLM"], [r2_mlr, r2_dlm],
                color=[C["amber"], C["green"]], alpha=0.7, width=0.5)
    axes[1].set_title(f"R2 (informative) | MLR={r2_mlr:.4f} DLM={r2_dlm:.4f}",
                      fontsize=10, color=C["text"])
    axes[1].set_ylabel("R2", fontsize=10)
    axes[1].set_ylim(0, max(r2_mlr, r2_dlm) * 1.3)
    axes[1].grid(axis="y", color=C["grid"], lw=0.6)

    plt.tight_layout()
    plt.savefig(OUTPUT_DIR / "verif5_dlm_vs_mlr.png",
                dpi=150, bbox_inches="tight", facecolor=fig.get_facecolor())
    plt.close()
    print(f"\n -> Figure: {OUTPUT_DIR}/verif5_dlm_vs_mlr.png")

    return {"aic_mlr": aic_mlr, "aic_dlm": aic_dlm,
            "aic_dlm_naive": aic_dlm_naive, "dic_dlm": dic_dlm, "p_d": p_d,
            "r2_mlr": r2_mlr, "r2_dlm": r2_dlm,
            "delta_aic": delta_aic}


# ═══════════════════════════════════════════════════════════════════════════════
# FULL VERIFICATION — RUN EVERYTHING
# ═══════════════════════════════════════════════════════════════════════════════

def run_full_validation(
    y: np.ndarray,
    dates: pd.DatetimeIndex,
    sigma_trend: float,
    sigma_seas: float,
    sigma_obs: float,
    sigma_ar: float = 0.0,
    rho: float = RHO,
    trend_dec: float = 0.0,
    mcmc_result: dict | None = None,
    proxies: np.ndarray | None = None,
    beta: np.ndarray | None = None,
) -> dict:
    """
    Runs the 5 verification levels and produces a summary report.
    """
    print("\n" + "="*60)
    print(" FULL VERIFICATION OF THE DLM + AR(1) MODEL -- OZONE")
    print("="*60)

    kf = kalman_filter(y, sigma_obs, sigma_trend, sigma_seas,
                       sigma_ar, proxies, beta, rho=rho)

    results = {}

    results["innov"] = check_innovations(kf, dates=dates)

    results["mcmc"] = check_mcmc_convergence(y, proxies=proxies, beta=beta)

    results["synth"] = test_synthetic_recovery(
        n=min(len(y), 450),
        true_sigma_trend=sigma_trend,
        true_sigma_seas=sigma_seas,
        true_sigma_obs=sigma_obs,
        true_sigma_ar=sigma_ar,
        true_rho=rho,
        true_trend_dec=trend_dec,
    )

    results["loyo"] = leave_one_year_out(y, sigma_trend, sigma_seas,
                                         sigma_obs, dates,
                                         sigma_ar=sigma_ar, rho=rho)

    results["comp"] = compare_dlm_mlr(y, sigma_trend, sigma_seas,
                                      sigma_obs, sigma_ar,
                                      proxies, beta, rho=rho,
                                      mcmc_result=mcmc_result)

    print("\n" + "="*60)
    print(" FINAL SUMMARY")
    print("="*60)
    checks = [
        ("White-noise innovations", results["innov"]["ok"]),
        ("MCMC convergence (Rhat/ESS)", results["mcmc"]["ok"]),
        ("Parameter recovery", results["synth"]["inside_params"]
         and results["synth"]["inside_trend"]),
        ("Leave-one-out coverage",
         results["loyo"]["total_coverage"] >= 0.80),
    ]
    for name, ok in checks:
        print(f" {'OK' if ok else 'FAIL'} {name}")

    print(f"\n -> Figures in {OUTPUT_DIR}/")
    return results


if __name__ == "__main__":
    print("Validation test on synthetic data (450 months)...")
    np.random.seed(0)
    n = 450
    t = np.arange(n)
    y_demo = (0.00833*t + 0.12*np.sin(2*np.pi*t/12)
              + np.random.normal(0, 0.04, n))
    dates_demo = pd.date_range("1994-01", periods=n, freq="MS")

    test_synthetic_recovery(n=n, n_mcmc=2000)
